### ISSUE TITLE
USER STORY 01: Branded Navbar

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/the-coffee-collective#1]
As a Site User, I can understand what the site aim is and my options from viewing the homepage, so that I can intuitively navigate the site and have a good e-commerce experience

---

### Acceptance Criteria:

* Acceptance Criteria 1: The site structure and layout should be clear and simple to navigate - all features within 2 clicks
* Acceptance Criteria 2: Site Users should be able to find products either from homepage adverts, Nav menu or Search function
* Acceptance Criteria 3: Site Users will have an option to register for a user account from the Navbar

### Tasks:

- [ ] Header with branding encompassed as part of the NavBar
- [ ] Option to explore site through main menu links; Useful Links, About Us, Contact Us, Accessibility Statement, User Agreement, Copyright Info
- [ ] Quick link to search products in Navbar
- [ ] Navbar will be fixed to support user navigation
- [ ] User account function added to Navbar
- [ ] NavBar will change in layout for mobile devices with collapsed menus
