### ISSUE TITLE
USER STORY 12: Product - Sale Items

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/the-coffee-collective#12]
As a Site User, I would like to see items on sale, so I can learn whether there is a better value product to purchase

---

### Acceptance Criteria:

* Acceptance Criteria 1: An enticing section of the homepage to draw users who enjoy purchasing sale items in
* Acceptance Criteria 2: Sale items visible through the Nav menu and filter on the Products page

### Tasks:

- [ ] Add a Sale Items section to the homepage carousal with a link to a list view page that details sale items- [ ] Task 2
- [ ] Add Sale items as a category to the Navmenu list
- [ ] Add Sale items to the filters for the Products page

**Comment by RickofManc** [comment]
This feature will be developed for a later release, and not for MVP.
