### ISSUE TITLE
USER STORY 14: Homepage - Carousal

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/the-coffee-collective#14]
As a Site Owner, I would like to use the homepage to promote items and key messages to users, so that I can drive traffic to the most beneficial areas
---

### Acceptance Criteria:

* Acceptance Criteria 1: The revolving carousal has an hero image with a banner advertising sale items
* Acceptance Criteria 2: A button within the banner allows Site Users to be navigated to the product listing for sale items

### Tasks:

- [ ] Create the carousal for the first section under the Navbar of the homepage
- [ ] Provide a minimum of three page promotions/information
- [ ] Set the revolutions to be automatic with additional ability for Site Users to manually cycle through the carousal
