### ISSUE TITLE
USER STORY 18: Checkout - Process

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/the-coffee-collective#18]
As a Site User, I would like to make a transaction without registering for a user account, as this is either a one off purchase or is my preference not to have a company hold my details
---

### Acceptance Criteria:

* Acceptance Criteria 1: Not registered users can checkout without an account whilst still maintaining all checkout functionality

### Tasks:

- [ ] Create checkout process that support users who do not want an account
- [ ] Ensure products can be removed, quantity upgraded
- [ ] Calculate delivery costs as part of the process - minimum spend equals free delivery
- [ ] Integrate email confirmation of the purchase
