### ISSUE TITLE
USER STORY 19: Checkout - with User Account

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/the-coffee-collective#19]
As a Site User, I would like my delivery details to be pre-populated when I come to pay, as this would be more convenient and ease my experience and time to purchase

---

### Acceptance Criteria:

* Acceptance Criteria 1: Pre-populated delivery details that can be overridden manually in the checkout area for authenticated users

### Tasks:

- [ ] Create checkout process that populates delivery info for authenticated users
- [ ] Ensure products can be removed, quantity upgraded
- [ ] Calculate delivery costs as part of the process - minimum spend equals free delivery
- [ ] Integrate email confirmation of the purchase
- [ ] Ensure User Account profile updates with transaction data
