### ISSUE TITLE
USER STORY 02: Navbar Search

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/the-coffee-collective#2]
As a Site User, I can search for products by entering descriptive words, so that I can find what I want quickly

---

### Acceptance Criteria:

* Acceptance Criteria 1: Search functionality is accessible from the Navbar
* Acceptance Criteria 2: All keywords, names, descriptions return results

### Tasks:

- [x] Develop search functionality
- [x] Create an icon and text field box on the Navbar
- [x] Ensure feature is accessible on all devices
