### ISSUE TITLE
USER STORY 20: Checkout - Retain Products

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/the-coffee-collective#20]
As a Site User, I would like to adjust the quantity or remove items from my shopping bag, in case I change my mind when assessing all my items before purchasing

---

### Acceptance Criteria:

* Acceptance Criteria 1: Site Users can increase or decrease the quantity of items within them shopping bag as part of the checkout process

### Tasks:

- [ ] Create functionality for increasing and decreasing each item within the shopping bag
- [ ] Add a button to remove an item complete is available
- [ ] Add a button to clear all items from the shopping bag

**Comment by RickofManc** [comment]
Bug preventing items being removed from the bag, and also the quantity decreasing to past 0 have both now been fixed.
