### ISSUE TITLE
USER STORY 21: User Account - Sign-up Page

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/the-coffee-collective#21]
As a Site User, I can register an account, so that I can comment and like posts

---

### Acceptance Criteria:

* Acceptance Criteria 1: Site Users are provided with a simple Form to complete in order to register an account
* Acceptance Criteria 2: Form fields should follow convention for sign-up forms
* Acceptance Criteria 3: Form buttons should enable the Form to be submitted or reset if an error has been made

### Tasks:

- [ ] Create HTML page for users to register
- [ ] Following fields will be required; First Name, Last Name, Email Address, Username, Password, Confirm Password
- [ ] Create a Sign Up and Reset button for under the above fields
- [ ] Link the Form with the database
- [ ] Provide a success message when form is submitted successfully
