### ISSUE TITLE
USER STORY 22: User Account - Sign-in Page

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/the-coffee-collective#22]
As a Site User, I can sign-in to my account, so that I can utilise member benefits

---

### Acceptance Criteria:

* Acceptance Criteria 1: Site Users will be able to sign-in from clicking a link in the Navbar menu
* Acceptance Criteria 2: Sites Users will be required to enter their Username and Password to sign-in
* Acceptance Criteria 3: A message should confirm to Site Users when they have successfully signed in
* Acceptance Criteria 4: A message should inform Site Users if the information entered was not valid, and to try again

### Tasks:

- [ ] Create HTML page for users to Sign-In
- [ ] Following Form fields will be required; Username, Password
- [ ] Create Submit and Reset buttons for the Form
- [ ] Add placeholders within the fields to support the users journey
- [ ] Display a message confirming that sign-in has been successful
- [ ] Display an error message if the data input was invalid
- [ ] Link the Form with the database
