### ISSUE TITLE
USER STORY 23: User Account - Sign-out Page

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/the-coffee-collective#23]
As a Site User, I can be asked to confirm my request to sign-out, so that I can cancel if requested in error

---

### Acceptance Criteria:

* Acceptance Criteria 1: Site Users will be able to sign-out from clicking a link in Navbar menu
* Acceptance Criteria 2: A page will display asking Site Users to confirm they would like to proceed to sign-out, or continue using the site
* Acceptance Criteria 3: If Site Users confirm they would like to sign-out they will be signed out and redirected to the home page
* Acceptance Criteria 4: A message should confirm to Site Users when they have successfully signed out
* Acceptance Criteria 5: If Site Users choose to continue using their account, access to features will remain

### Tasks:

- [ ] Create a link in Navbar menu  called 'Sign-out'
- [ ] The link will be visible only when a Site User is signed in
- [ ] When clicked a page will display asking the Site User to confirm they would like to sign-out
- [ ] Create route to return Site User to homepage without access to features when the Sign-out button is clicked
- [ ] Add messaging to confirm successfully signed out
