### ISSUE TITLE
USER STORY 24: User Account - Profile Updating

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/the-coffee-collective#24]
As a Site User, I can view and change profile details, so that they are correct when I come to checkout

---

### Acceptance Criteria:

* Acceptance Criteria 1: Site Users can navigate to a restricted page that provides all the relevant profile details
* Acceptance Criteria 2: Site Users can amend any part of the information and save the changes
* Acceptance Criteria 3: A success message will confirm the changes have been saved

### Tasks:

- [ ] Create a profile page that is only available to sign-in users
- [ ] Ensure the page pre-populates with their information
- [ ] Site Users can update their Username, First Name, Last Name, Email Address, Delivery Address
- [ ] Provide a success message when the updates have been made
- [ ] Ensure the data is updated on the database and that new data is pre-populated for checkout
