### ISSUE TITLE
USER STORY 25: User Account - Product Review

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/the-coffee-collective#25]
As a Site User, I can add a product review, so that I can inform potential customers of what they might expect

---

### Acceptance Criteria:

* Acceptance Criteria 1:  Authenticated users will be able to post a review on a detailed product page
* Acceptance Criteria 2:  Site Users will be limited to a conventional 280 characters
* Acceptance Criteria 3:  A button clearly stating to 'Submit' their review will be available
* Acceptance Criteria 4:  Site Users will be able to see their post instantly

### Tasks:

- [ ] Create a blank text box to be displayed underneath a Product
- [ ] Signed-in Site Users will be able to click within the area to start typing a review
- [ ] Placeholder text and a character count will indicate a limit of 280 characters
- [ ] A 'Submit' button will be displayed underneath the text box
- [ ] Potentially add a rating 1-5 as part of the review using coffee cup/bean icon
