### ISSUE TITLE
USER STORY 03: Footer

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/the-coffee-collective#3]
As a Site User, I can use the Footer for navigation, so that I can learn more about the business
---

### Acceptance Criteria:

* Acceptance Criteria 1: Footer is located at the bottom of every page
* Acceptance Criteria 2: Footer provides links that are clear and accessible

### Tasks:

- [ ] Create a Footer in the base template that contains all relevant business links
- [ ] Ensure colour and text combinations meet accessibility standards
- [ ] Layout change for mobile to large devices
