### ISSUE TITLE
USER STORY 30: Newsletter Sign-up

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/the-coffee-collective#30]
As Site Owner, I would like Site Users to register for a monthly newsletter, so that I can build a relationship with customers and promote specific products

---

### Acceptance Criteria:

* Acceptance Criteria 1: Site User can enter an email address and receive a success message within the browser
* Acceptance Criteria 2: Site Users will receive confirmation of sign-up to their inbox

### Tasks:

- [ ] Create a section of the homepage for newsletter sign-up
- [ ] Detail the benefits of signing up
- [ ] Provide success/error messaging when email address is input and submitted
- [ ] Provide an email confirmation to users inbox
- [ ] If time permits create a newsletter template
