### ISSUE TITLE
USER STORY 31: About Us Page

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/the-coffee-collective#31]
As Site Owner, I would like to provide Site Users with more information on the business, so that Site Users can understand the history, manufacturing process, culture etc. with a view to increasing trust and building relationships

---

### Acceptance Criteria:

* Acceptance Criteria 1: Site Users will be able to access this page from either the Footer
* Acceptance Criteria 2: Site Users will be navigated to a new page which informs of who, when, why and what the business is about
* Acceptance Criteria 3: Site Users will be offered an opportunity to register an account following learning more about the business

### Tasks:

- [ ] Create a HTML page that provide information on who, when, why and what the business is about
- [ ] Include an image of the family to create friendly vibe with Site Users
- [ ] Add a link to the page within the Footer
- [ ] Within the About Us page, add a link to the Sign-up page and promote member benefits
