### ISSUE TITLE
USER STORY 32: Contact Us Page

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/the-coffee-collective#32]
As Site Owner, I can provide a contact form for Site Users, so they can provide feedback, request products, features etc.

---

### Acceptance Criteria:

* Acceptance Criteria 1: Site Users will be able to access this page from the Footer
* Acceptance Criteria 2: Site Users will be introduced to the FAQ page in case they hadn't already viewed this information and could of had their question answered
* Acceptance Criteria 3: Site Users will be provided with a Form to complete, learning where the Form is sent and when to expect a response
* Acceptance Criteria 4: Site Users will be redirected to the homepage when the form has been successfully submitted

### Tasks:

- [ ] Create a HTML page that provides a Form users complete when wanting to make contact
- [ ] Form will require the Site Users Name, Email Address, Subject and Message
- [ ] Provide a success message on form submission with redirection back to the homepage
- [ ] Add a link to the page within the Footer
- [ ] Ensure messages can be managed from the Django Admin and received externally to Site Admin
