### ISSUE TITLE
USER STORY 37: Website Responsiveness

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/the-coffee-collective#37]
As a Site User, I can access the site on differing devices, so I can interact with content on my preferred device

---

### Acceptance Criteria:

* Acceptance Criteria 1: Successful tests for Responsiveness using Developer Tools
* Acceptance Criteria 2: Successful tests for Responsiveness through manual testing on differing devices

### Tasks:

- [ ] Create media query for Mobile users at Max-width: 567px
- [ ] Create media queries for Tablet users at Min-width: 567-768px
- [ ] Create media queries for Desktop users at Min-width : 768-992px
- [ ] Create media queries for Desktop users at Min-width : 992-1200px
- [ ] Create media queries for Desktop users at Min-width : 1200px plus
- [ ] Centralise content for 5k screens with max body width of circa 80%
