### ISSUE TITLE
USER STORY 38: Wish List

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/the-coffee-collective#38]
As a registered user/member, I can save products I may wish to buy, so that I can come back and see a short-list when I'm ready to purchase

---

### Acceptance Criteria:

* Acceptance Criteria 1: Signed-in users have access to using an optional wish list
* Acceptance Criteria 2: Signed-in users can add items to their wish list from the product page and remove from the wish list page
* Acceptance Criteria 3: The wish list feature is not available to non members

### Tasks:

- [ ] Create the model , views and url for the Wish List
- [ ] Create a html page for the Wish List
- [ ] Add relevant links to the Wish List page
- [ ] Create buttons and functionality to add items to the Wish List from the products page
- [ ] Create button in Wish List page to remove items from the Wish List

**Comment by RickofManc** [comment]
This feature was considered after the main build was complete following concern the level of customisation from CI walk through project Boutique Ado would be insufficient and therefore result in a failed assessment.
