### ISSUE TITLE
USER STORY 04: Brand Logo

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/the-coffee-collective#4]
As Site Owner, I want a brand logo, so Site Users can easily learn the type of products being sold

---

### Acceptance Criteria:

* Acceptance Criteria 1: A logo that is identifiable as relating to coffee products that will help build the brand
* Acceptance Criteria 2: Logo to be used within the Navbar

### Tasks:

- [ ] Research competitor and conventional branding for similar e-commerce sites
- [ ] Choose an accessible colour contrast scheme to viewed by all Site Users
- [ ] Add logo as favicon

**Comment by RickofManc** [comment]
Logo added as favicon - however opted not to include in Brand Navbar at the moment.
