### ISSUE TITLE
USER STORY 05: Site Admin - Add Products

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/the-coffee-collective#5]
As a Site Owner, I can add products to the site, so I can manage the content and adapt to changes in stock and competition

---

### Acceptance Criteria:

* Acceptance Criteria 1: Successfully add a product from either the back or front end

### Tasks:

- [ ] Create Product app Model that will enable the addition of products to the site
- [ ] Add Model to the Admin site
- [ ] Add Model to the Views so the functionality is available on the front end
