### ISSUE TITLE
USER STORY 07: Site Admin - Remove Products

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/the-coffee-collective#7]
As a Site Owner, I can remove products from the site, so I can manage the content and adapt to changes in stock and competition

---

### Acceptance Criteria:

* Acceptance Criteria 1: Successfully remove a product from either the back or front end

### Tasks:

- [ ] Create a Delete Model that will enable the update of existing products
- [ ] Add Model to the Admin site
- [ ] Add Model to the Views so the functionality is available on the front end
