### ISSUE TITLE
USER STORY 08: Product - Details

### ISSUE THREAD

**Issue by RickofManc** [RickofManc/the-coffee-collective#8]
As a Site User, I can learn about a product from the details provided, so that I can make an informed decision to purchase

---

### Acceptance Criteria:

* Acceptance Criteria 1: Sufficient details on the product category pages that offer Title, Subtitle, Price with a view to enticing the user to click and learn more
* Acceptance Criteria 2: Product page with full descriptions in addition to those highlighted in 1

### Tasks:

- [ ] Create a Product Model for title, subtitle, category, description, price, user rating, and image
- [ ] Create card for products in a list view with a subset of information, and different card for single page product view
- [ ] Add buttons for users to 'Learn More' or 'Add to Bag'
- [ ] Add functionality to buy more than one
- [ ] Add functionality to choose a size (if product applicable)
